### ISSUE TITLE
Impossible to have in same /joint_states  topic Wheels and P&Tilt !!

### ISSUE THREAD

**Issue by elpimous** [yujinrobot/kobuki#388]
Hello, I encounter a problem with my kobuki robot (with pan and tilt head)
The kobuki works perfectly !! Thanks for this perfect robot !! And the docking station !!
https://plus.google.com/photos/photo/115946641037512570220/6532499646122540258?hl=fr 
LOL

But, when launching kobuki_node minimal.launch,
and same time dynamixels.launch,

I receive this topic : 

rostopic echo /joint_states 
```
---
header: 
  seq: 1207
  stamp: 
    secs: 1522001104
    nsecs: 870637822
  frame_id: ''
name: [wheel_left_joint, wheel_right_joint]
position: [0.0, 0.0]
velocity: [0.0, 0.0]
effort: [0.0, 0.0]
---
header: 
  seq: 218
  stamp: 
    secs: 1522001104
    nsecs: 878241062
  frame_id: "base_link"
name: [head_pan_joint, head_tilt_joint]
position: [0.0, 0.0]
velocity: [0.0, 0.0]
effort: [0.0, 0.0]
---
```
I use kobuki stock apps,
here is my dynamixel.launch : 

```
<launch>
   <!-- Start the Dynamixel low-level driver manager with parameters -->
   <node name="dynamixel_manager" pkg="dynamixel_controllers"
      type="controller_manager.py" required="true" output="screen">
      <rosparam>
         namespace: alfred_dynamixel_manager
         serial_ports:
            dynamixel_ax12:
               port_name: /dev/ttyACM0
               baud_rate: 1000000
               min_motor_id:  1
               max_motor_id: 4
               update_rate: 20
      </rosparam>
   </node>
   
    <!-- Load the joint controller configuration from a YAML file -->
    <rosparam file="$(find alfred_launcher)/config/dynamixel_params.yaml" command="load"/>

   <!-- Start the head pan and tilt controllers -->
   <node name="dynamixel_controller_spawner_ax12" pkg="dynamixel_controllers"
   type="controller_spawner.py"
        args="--manager=alfred_dynamixel_manager
              --port=dynamixel_ax12
              --type=simple
        head_pan_joint
        head_tilt_joint"
        output="screen" />

   <!-- Start the Dynamixel Joint States Publisher -->
   <node name="dynamixel_joint_states_publisher" pkg="alfred_launcher" type="dynamixel_joint_state_publisher.py" output="screen" />
```

I think it's a small error anywhere, but can't find it. Please anyone, small help ?
